package com.shopstack.model;

public enum StockMovementType {
    INBOUND_RESTOCK,
    VENDOR_STOCK_TRANSFER,
    ORDER_ALLOCATION,
    PICK_CONFIRMED,
    PACK_VERIFIED,
    SHIPMENT_PREPARED,
    SHIPMENT_DISPATCH,
    ALLOCATION_RELEASED,
    MANUAL_ADJUSTMENT,
    RETURN_RECEIVED,
    QC_RESTOCKED,
    QC_QUARANTINED
}
