spring.application.name=javaenterprise
spring.datasource.url=jdbc:postgresql://localhost:5432/shopstack
spring.datasource.username=postgres
spring.datasource.password=@Gautham200
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=4f8b2d9c7a1e6f3b5c8d0a9e2f7b1c6d8e4f9a2b7c5d1e3f6a8b0c2d4e7f9a1
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG



logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Razorpay Configuration (Use your Test Keys for now)
razorpay.key.id=rzp_test_TPL0s51UBXsXRf
razorpay.key.secret=n2RDw3dzn5cRe6w1dB4ElEo6

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singaravelusgauthaman@gmail.com
spring.mail.password=txdmcgediiconzfc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

