import { useEffect, useState } from "react";
import AdminSidebar from "./AdminSidebar";
import "./Admin.css";
import "./AdminCoupons.css";
import "./AdminCouponsOverrides.css";

const emptyCoupon = { code: "", discountType: "PERCENTAGE", discountValue: "", startDate: "", expiryDate: "", usageLimit: "", active: true };
const token = () => localStorage.getItem("token");

function notifyCouponsUpdated() {
  const timestamp = Date.now().toString();
  localStorage.setItem("shopstack-coupons-updated", timestamp);
  window.dispatchEvent(new CustomEvent("shopstack-coupons-updated", { detail: timestamp }));
}

export default function AdminCoupons() {
  const [coupons, setCoupons] = useState([]); const [form, setForm] = useState(emptyCoupon); const [editingId, setEditingId] = useState(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("https://shopstack-backend-gjv6.onrender.com/api/admin/coupons", { headers: { Authorization: `Bearer ${token()}` } }); if (!response.ok) throw new Error("Unable to load coupons."); setCoupons(await response.json()); }
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  function change(event) { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); }
  function edit(coupon) { setEditingId(coupon.id); setForm({ code: coupon.code || "", discountType: coupon.discountType || "PERCENTAGE", discountValue: coupon.discountValue ?? "", usageLimit: coupon.usageLimit ?? "", startDate: coupon.startDate?.slice(0, 16) || "", expiryDate: coupon.expiryDate?.slice(0, 16) || "", active: coupon.active ?? true }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event) { event.preventDefault(); setError(""); setMessage(""); const payload = { ...form, discountValue: Number(form.discountValue), usageLimit: form.usageLimit === "" ? null : Number(form.usageLimit) }; const response = await fetch(`https://shopstack-backend-gjv6.onrender.com/api/admin/coupons${editingId ? `/${editingId}` : ""}`, { method: editingId ? "PUT" : "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.message || "Unable to save coupon."); return; } notifyCouponsUpdated(); setMessage(editingId ? "Coupon updated." : "Coupon created."); setEditingId(null); setForm(emptyCoupon); load().catch((e) => setError(e.message)); }
  async function remove(id) { if (!window.confirm("Delete this coupon?")) return; const response = await fetch(`https://shopstack-backend-gjv6.onrender.com/api/admin/coupons/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token()}` } }); if (response.ok) { notifyCouponsUpdated(); setCoupons((items) => items.filter((item) => item.id !== id)); } else setError("Unable to delete coupon."); }
  return <div className="admin-dashboard-container"><AdminSidebar /><main className="admin-main admin-coupons-main"><div className="coupons-page-heading"><div><span className="admin-eyebrow">SALES TOOLS</span><h1>Coupons</h1><p>Create discounts and control their availability.</p></div></div><section className="coupon-editor"><h2>{editingId ? "Edit coupon" : "Create a coupon"}</h2><form onSubmit={submit} className="coupon-form"><label>Coupon Code<input name="code" value={form.code} onChange={change} placeholder="WELCOME20" required /></label><label>Discount Type<select name="discountType" value={form.discountType} onChange={change}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount</option></select></label><label>Discount Value<input name="discountValue" type="number" min="0.01" step="0.01" value={form.discountValue} onChange={change} required /></label><label>Usage Limit<input name="usageLimit" type="number" min="1" step="1" value={form.usageLimit} onChange={change} placeholder="Unlimited" /></label><label>Start Date<input name="startDate" type="datetime-local" value={form.startDate} onChange={change} required /></label><label>Expiry Date<input name="expiryDate" type="datetime-local" value={form.expiryDate} onChange={change} required /></label><label className="coupon-active"><input name="active" type="checkbox" checked={form.active} onChange={change} /> Active</label><div className="coupon-form-actions"><button type="submit">{editingId ? "Save Changes" : "Create Coupon"}</button>{editingId && <button type="button" className="coupon-cancel" onClick={() => { setEditingId(null); setForm(emptyCoupon); }}>Cancel</button>}</div></form>{error && <p className="coupon-error">{error}</p>}{message && <p className="coupon-success">{message}</p>}</section><section className="coupons-panel"><div className="coupons-panel-heading"><h2>All coupons</h2><span>{coupons.length} total</span></div><div className="coupons-table-wrap"><table className="coupons-table"><thead><tr><th>Code</th><th>Discount</th><th>Validity</th><th>Usage</th><th>Status</th><th>Actions</th></tr></thead><tbody>{coupons.map((coupon) => <tr key={coupon.id}><td><strong>{coupon.code}</strong></td><td>{coupon.discountType === "PERCENTAGE" ? `${coupon.discountValue}%` : `₹${coupon.discountValue}`}</td><td><small>{new Date(coupon.startDate).toLocaleDateString()} – {new Date(coupon.expiryDate).toLocaleDateString()}</small></td><td>{coupon.usageCount}{coupon.usageLimit ? ` / ${coupon.usageLimit}` : " / ∞"}</td><td><span className={`coupon-status ${coupon.active ? "active" : "inactive"}`}>{coupon.active ? "Active" : "Inactive"}</span></td><td><button className="coupon-action" onClick={() => edit(coupon)}>Edit</button><button className="coupon-action danger" onClick={() => remove(coupon.id)}>Delete</button></td></tr>)}</tbody></table>{coupons.length === 0 && <div className="coupons-empty">No coupons created yet.</div>}</div></section></main></div>;
}
